name: "GCP Cloud run deploy"

on:
  workflow_run:
    workflows:
      - "Build and Upload"
    types:
      - completed

env:
  PROJECT_ID: vegetation-407619
  IMAGE: revolko/vegetation:latest
  SERVICE: vegetation
  REGION: europe-central2

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_JSON }}'
          token_format: 'access_token'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}
          env_vars: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_HOST=/cloudsql/${{ secrets.POSTGRES_HOST }}
          flags: '--allow-unauthenticated --add-cloudsql-instances ${{ secrets.POSTGRES_HOST }}'
